SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%'
   OR CITY NOT LIKE 'E%'
   OR CITY NOT LIKE 'I%'
   OR CITY NOT LIKE 'O%'
   OR CITY NOT LIKE 'U%'
   OR CITY NOT LIKE '%a'
   OR CITY NOT LIKE '%e'
   OR CITY NOT LIKE '%i'
   OR CITY NOT LIKE '%o'
   OR CITY NOT LIKE '%u';